// This file is automatically generated. Do not edit it directly.
import { Pool } from 'pg'


const DATABASE_URL = process.env.DATABASE_URL;


if (!DATABASE_URL) {
    throw new Error('DATABASE_URL environment variable is required')
}

export const pool = new Pool({
    connectionString: DATABASE_URL,
    ssl: true,
    max: 2,
    idleTimeoutMillis: 5000
})
