/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMembersRouteImport } from './routes/api/members'
import { Route as ApiMembersFilesDeliveryRouteImport } from './routes/api/members/files/delivery'
import { Route as ApiMembersExportCsvRouteImport } from './routes/api/members.export.csv'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMembersRoute = ApiMembersRouteImport.update({
  id: '/api/members',
  path: '/api/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMembersFilesDeliveryRoute = ApiMembersFilesDeliveryRouteImport.update({
  id: '/files/delivery',
  path: '/files/delivery',
  getParentRoute: () => ApiMembersRoute,
} as any)
const ApiMembersExportCsvRoute = ApiMembersExportCsvRouteImport.update({
  id: '/export/csv',
  path: '/export/csv',
  getParentRoute: () => ApiMembersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/members': typeof ApiMembersRouteWithChildren
  '/api/members/export/csv': typeof ApiMembersExportCsvRoute
  '/api/members/files/delivery': typeof ApiMembersFilesDeliveryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/members': typeof ApiMembersRouteWithChildren
  '/api/members/export/csv': typeof ApiMembersExportCsvRoute
  '/api/members/files/delivery': typeof ApiMembersFilesDeliveryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/members': typeof ApiMembersRouteWithChildren
  '/api/members/export/csv': typeof ApiMembersExportCsvRoute
  '/api/members/files/delivery': typeof ApiMembersFilesDeliveryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/members'
    | '/api/members/export/csv'
    | '/api/members/files/delivery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/members'
    | '/api/members/export/csv'
    | '/api/members/files/delivery'
  id:
    | '__root__'
    | '/'
    | '/api/members'
    | '/api/members/export/csv'
    | '/api/members/files/delivery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMembersRoute: typeof ApiMembersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/members': {
      id: '/api/members'
      path: '/api/members'
      fullPath: '/api/members'
      preLoaderRoute: typeof ApiMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/members/files/delivery': {
      id: '/api/members/files/delivery'
      path: '/files/delivery'
      fullPath: '/api/members/files/delivery'
      preLoaderRoute: typeof ApiMembersFilesDeliveryRouteImport
      parentRoute: typeof ApiMembersRoute
    }
    '/api/members/export/csv': {
      id: '/api/members/export/csv'
      path: '/export/csv'
      fullPath: '/api/members/export/csv'
      preLoaderRoute: typeof ApiMembersExportCsvRouteImport
      parentRoute: typeof ApiMembersRoute
    }
  }
}

interface ApiMembersRouteChildren {
  ApiMembersExportCsvRoute: typeof ApiMembersExportCsvRoute
  ApiMembersFilesDeliveryRoute: typeof ApiMembersFilesDeliveryRoute
}

const ApiMembersRouteChildren: ApiMembersRouteChildren = {
  ApiMembersExportCsvRoute: ApiMembersExportCsvRoute,
  ApiMembersFilesDeliveryRoute: ApiMembersFilesDeliveryRoute,
}

const ApiMembersRouteWithChildren = ApiMembersRoute._addFileChildren(
  ApiMembersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMembersRoute: ApiMembersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
